const currentWeather = {
  latitude: 17.375,
  longitude: 78.5,
  generationtime_ms: 0.07009506225585938,
  utc_offset_seconds: 19800,
  timezone: 'Asia/Kolkata',
  timezone_abbreviation: 'IST',
  elevation: 515,
  current_units: {
    time: 'iso8601',
    interval: 'seconds',
    temperature_2m: '°C',
    relative_humidity_2m: '%',
    apparent_temperature: '°C',
    is_day: '',
    precipitation: 'mm',
    rain: 'mm',
    showers: 'mm',
    snowfall: 'cm',
    weather_code: 'wmo code',
    wind_speed_10m: 'km/h',
  },
  current: {
    time: '2024-12-25T14:00',
    interval: 900,
    temperature_2m: 26.5,
    relative_humidity_2m: 63,
    apparent_temperature: 28.2,
    is_day: 1,
    precipitation: 0,
    rain: 0,
    showers: 0,
    snowfall: 0,
    weather_code: 2,
    wind_speed_10m: 11.4,
  },
};
